# Generated by Django 2.0a1 on 2017-09-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='gif',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
